Measuring and calculating Headphone impedance.  <br>
<hr>
09-Jul-23      CBL       Original 
<hr>
references: <br>
<hr>
descripton: <br>
<ul>
    <li>Put a precision resistor in the return line (ground side) of the headphones under test. </li>
    <li> put a scope across the source and record the voltage/phase into the circuit. </li>
    <li> put a scope across the resistor and record the voltage/phase across the resistor. </li> 
    <li> sweep the frequencies and measure the response.</li>
</ul>
<hr> 

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import math
import scipy.constants   as konst

For the circuit we have the following relation: <br> 
$V_{source} = I Z + I R $ where I is the current running through the loop. <br> 
The voltage measured across the resistor is $V_{out} = IR $, solving for Z we have: <br>
$Z = {V_{source}-V_{out}\over{I}} $ and solving for I: $I = {V_{out}\over{R}} $ and substituting: <br> 
$Z = ({V_{source}\over{V_{out}} }  - 1) R $

In [5]:
def StraightResistance(Vin, Vout, RSeries):
    """
    Look at the unknown resistance based on the voltage drop across the resistor. 
    @param Vin  - input voltage across the 2 terminal system
    @param Vout - voltage across the resistor
    @param RSeries - Series resistor
    """
    Z = (Vin/Vout -1) * RSeries
    return Z

In [17]:
def XFromPhase(Resistance, Phase):
    """ 
    determine X from the phase angle and the resistance. 
    @param Resistance in ohms
    @param Phase in radians
    tan(phase) = X/R
    """
    return Resistance * np.tan(Phase)
    

In [6]:
# Harvey Ellis Electromagnetics
# voltages measured are pp on the scope. 
# noise level is about 10mV
#
f       = np.array([400, 1000, 2000, 5000, 10000]) # Hz
RSeries = 40 # ohms
Vin     = np.array([352, 304, 400, 400, 416]) # millivolts
Vout    = np.array([80, 54, 40, 30, 21])      # millivolts
Z       = StraightResistance(Vin, Vout, RSeries)
print(Z)

[136.         185.18518519 360.         493.33333333 752.38095238]


<hr>
Western Electric 194W headphones <br>
https://oldheadphones.com/crystal/gallery/gallerywe.html <br>
<hr>
1918 vintage <br> 
The impedance is given in AC ohms at 22,700 ohms as well as DC resistance at 2,200 ohms.

In [8]:
# Western Electric 194W
f       = np.array([2000, 5000, 10000]) #Hz
RSeries = 40 # ohms 
Vin     = np.array([416, 416, 416])     # mV
Vout    = np.array([10,10,10])          # mV
# This is inconclusive
Z       = StraightResistance(Vin, Vout, RSeries)
print(Z)

[1624. 1624. 1624.]


In [9]:
# Western Electric 194W, second time around with new resistor
f       = np.array([400, 1000, 2000, 5000]) # Hz
RSeries = 240 # ohms
Vin     = np.array([416, 416, 416, 416])    # mV
Vout    = np.array([25, 17.2, 14, 12])      # mV
# This is inconclusive
Z       = StraightResistance(Vin, Vout, RSeries)
print(Z)

[3753.6        5564.65116279 6891.42857143 8080.        ]


In [10]:
# Western Electric 194W, second time around with new resistor
f       = np.array([400, 1000]) # Hz
RSeries = 1000 # ohms
Vin     = np.array([416, 416])    # mV
Vout    = np.array([80, 48])      # mV
# This is inconclusive
Z       = StraightResistance(Vin, Vout, RSeries)
print(Z)

[4200.         7666.66666667]


Federal Type 53W <br> 
https://www.radiomuseum.org/r/federal_ra_liberty_headphones_53_w.html <br> 
1921<br>
2200 ohms <br>

In [13]:
# Federal Type 53W, has 2200 ohms printed on it. 
f       = np.array([400, 1000, 2000, 5000]) # Hz
RSeries = 1000 # ohms
Vin     = np.array([416, 416, 416, 416])    # mV
Vout    = np.array([60, 36, 24, 24])      # mV
Z       = StraightResistance(Vin, Vout, RSeries)/(2*np.sqrt(2))
print(Z)

[2097.75011752 3731.95245626 5774.70537969 5774.70537969]


DCM H-43 B/U <br>
https://buyaircraftparts.com/part-number/h-43bu_00-651-7372 <br>
Impedance: 22,000 ohms <br>
1940's WWII vintage <br> 

In [14]:
# DCM H-43 B/U 
f       = np.array([400, 1000, 2000, 5000]) # Hz
RSeries = 1000 # ohms
Vin     = np.array([416, 416, 416, 416])    # mV
Vout    = np.array([74, 53, 44, 40])      # mV
Z       = StraightResistance(Vin, Vout, RSeries)/(2*np.sqrt(2))
print(Z)

[1633.98999436 2421.50718463 2989.13321138 3323.40187158]


In [18]:
# Finally, for the Western Electric 194W look at the phases. 
R  = 1000.0     # ohms
dt = 200.0e-6   # seconds
f  = 1000.0     # Hz
T  = 1.0/f      # seconds
phase = dt/T
print("DUT phase shift: ", phase, " radians and resulting reactance: ", XFromPhase(R,phase))

DUT phase shift:  0.2  radians and resulting reactance:  202.7100355086725


Overall none of these measurements worked!