In [2]:
#
# Example for doing 3-D rotations. 
#
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html
#
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.transform import Rotation as R

07-Jan-22   CBL Original

In [29]:
# Vector of data to operate on
X = np.array([1,0,0])

# Single rotation, multiple angles Rx, Ry, Rz
r = R.from_rotvec([0, 0, np.pi/2])
r.as_euler('zxy', degrees=True)  # odd that this show as Phi first
#r.as_matrix()

array([90.,  0.,  0.])

In [25]:
r.as_euler('zxy', degrees=True).shape

(3,)

In [26]:
XP = r.apply(X)
XP

array([2.22044605e-16, 1.00000000e+00, 0.00000000e+00])

In [30]:
XP = r.apply(XP)
XP

array([-1.0000000e+00,  4.4408921e-16,  0.0000000e+00])

In [8]:
# multiple rotations, R1 R2 R3
r2 = R.from_rotvec([
        [0, 0, np.pi/2],
        [0, -np.pi/3, 0],
        [np.pi/4, 0, 0]])
r2.as_euler('zxy', degrees=True)

array([[ 90.,   0.,   0.],
       [  0.,   0., -60.],
       [  0.,  45.,   0.]])

In [9]:
r2.as_euler('zxy', degrees=True).shape

(3, 3)

In [18]:
XP = r2.apply(X)
XP

array([[2.22044605e-16, 1.00000000e+00, 0.00000000e+00],
       [5.00000000e-01, 0.00000000e+00, 8.66025404e-01],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00]])